#include "platform.h"
#include "game.h"
#include "assets_bitplanes.h"
#include <stddef.h>
#include <stdint.h>
#define W 320
#define H 200
#define BLACK 0x0000
#define WHITE 0xffff
#define SEA 0x0452
#define SKY 0x65df
#define NAVY 0x0010
#define GOLD 0xfda0
#define RED 0xf800
#define GREEN 0x07e0
#define CYAN 0x07ff
#define GREY 0x8410
#define LAND 0x39e7
#define RACES 5
#define SIM_FRAMES_PER_SECOND 3
#define START_COUNTDOWN_SECONDS 600
#define RACE_LIMIT_SECONDS 1800
#define PREVAILING_SW_HEADING 0
#define START_LINE_Y 146
#define START_LINE_LEFT 94
#define START_LINE_RIGHT 226
#define START_BOX_LEFT 70
#define START_BOX_RIGHT 250
#define START_BOX_BOTTOM 178
#define COURSE_COUNT 3
#define COURSE_MARKS_MAX 6
#define FINISH_Y 158
#define FINISH_BOAT_X 74
#define FINISH_BUOY_X 226
#define TOP_VIEW_ENTER 65
typedef enum {ST_TITLE,ST_MODE,ST_TEAM,ST_MANAGER,ST_BRIEF,ST_LOBBY,ST_RACE,ST_RESULT,ST_SEASON} screen_t;
typedef enum {RULE_NONE,RULE_PORT,RULE_WINDWARD,RULE_ASTERN,RULE_TACKING,RULE_CONTACT,RULE_MARK_ROOM,RULE_MARK_TOUCH} rule_t;
typedef struct {char name[18],code[4];uint16_t color;uint8_t speed,turn,crew;} team_t;
typedef struct {int32_t x,y;int16_t heading,speed;int8_t tack;uint8_t team,leg,finished,penalty,spinnaker,started,start_ready,entered_box,tacking,tack_timer,penalty_turn,rule,mark_touch;uint16_t finish_time;} boat_t;
typedef struct {char name[18];int fee,win_bonus;uint8_t min_wins;} sponsor_t;
/* GCC may lower small descriptor assignments to memcpy even under
   -ffreestanding.  Portable cartridges do not link a C library. */
void *memcpy(void *dst,const void *src,size_t size){volatile uint8_t *d=(volatile uint8_t *)dst;const volatile uint8_t *s=(const volatile uint8_t *)src;size_t i;for(i=0;i<size;i++)d[i]=s[i];return dst;}
static const team_t teams[4]={{"PARTENOPE 12","ITA",CYAN,6,7,7},{"LIBECCIO CORSE","ITA",RED,7,6,6},{"ATLANTIC UNION","USA",WHITE,7,7,5},{"SOUTHERN CROSS","AUS",0xffe0,6,6,8}};
static const sponsor_t sponsors[4]={{"GULF MARINE",18,7,0},{"VESUVIO TECH",26,11,1},{"CAPRI LUX",38,16,2},{"PARTENOPE GLOBAL",55,24,3}};
static const char race_names[RACES][16]={"SANTA LUCIA","VESUVIUS CUP","CAPRI PASSAGE","SORRENTO RACE","NAPLES FINAL"};
static const char course_names[COURSE_COUNT][20]={"WINDWARD / RUN","OLYMPIC TRIANGLE","1992 IACC Z"};
static const char rule_names[8][20]={"CLEAR","PORT / STARBOARD","WINDWARD / LEEWARD","CLEAR ASTERN","WHILE TACKING","AVOID CONTACT","MARK ROOM","TOUCHED MARK"};
static const uint8_t course_len[COURSE_COUNT]={3,5,6};
static const int16_t course_x[COURSE_COUNT][COURSE_MARKS_MAX]={{160,160,160,0,0,0},{160,280,160,160,160,0},{160,280,160,160,40,160}};
static const int16_t course_y[COURSE_COUNT][COURSE_MARKS_MAX]={{45,132,45,0,0,0},{45,92,132,45,132,0},{45,88,132,45,88,45}};
static const int8_t sin32[32]={0,6,12,18,23,27,30,31,31,30,27,23,18,12,6,0,-6,-12,-18,-23,-27,-30,-31,-31,-31,-30,-27,-23,-18,-12,-6,0};
static nacup_sprite_t jib_yacht_sprite,spin_yacht_sprite,mark_sprite,cup_sprite;static boat_t boats[4];static screen_t screen;
static uint32_t last_input,frame,rng=0x97ca1997u;static int team_sel,menu,points[4],race_no,money,hull,sails,crew,strategy,sponsor,wins,last_prize,wind_dir,wind_power,race_clock,start_clock,race_frames,signal_sound_frames,course_sel;static uint8_t multiplayer,peer_count,player_rank,local_ready,start_line_active,top_view_mode,result_order[4];
static uint32_t rnd(void){rng^=rng<<13;rng^=rng>>17;rng^=rng<<5;return rng;}static int absi(int n){return n<0?-n:n;}static int clamp(int n,int lo,int hi){return n<lo?lo:n>hi?hi:n;}
static void number(int x,int y,int n,uint16_t fg,uint16_t bg){char b[8];int i=6;b[7]=0;if(n<0)n=0;do{b[i--]=(char)('0'+n%10);n/=10;}while(n&&i>=0);while(i>=0)b[i--]=' ';prg32_gfx_text8(x,y,b,fg,bg);}static void digit(int x,int y,int n,uint16_t fg,uint16_t bg){char b[2];b[0]=(char)('0'+clamp(n,0,9));b[1]=0;prg32_gfx_text8(x,y,b,fg,bg);}static void clock_mmss(int x,int y,int n,uint16_t fg,uint16_t bg){char b[6];int m;if(n<0)n=0;m=clamp(n/60,0,99);b[0]=(char)('0'+m/10);b[1]=(char)('0'+m%10);b[2]=':';b[3]=(char)('0'+(n%60)/10);b[4]=(char)('0'+n%10);b[5]=0;prg32_gfx_text8(x,y,b,fg,bg);}static void box(int x,int y,int w,int h,uint16_t e,uint16_t f){prg32_gfx_rect(x,y,w,h,e);prg32_gfx_rect(x+2,y+2,w-4,h-4,f);}
static void sprite(nacup_sprite_t *s,const uint8_t *pixels,const uint16_t *palette,uint16_t w,uint16_t h,uint16_t frames,uint8_t bpp,int16_t transparent){s->planes=pixels;s->palette=palette;s->width=w;s->height=h;s->frame_count=frames;s->plane_count=bpp;s->palette_count=(uint16_t)(1u<<bpp);s->transparent_index=transparent;}
static void setup_sprites(void){sprite(&jib_yacht_sprite,nacup_jib_yacht_planes,nacup_yacht_palette0,32,32,16,4,0);sprite(&spin_yacht_sprite,nacup_spin_yacht_planes,nacup_yacht_palette0,32,32,16,4,0);sprite(&mark_sprite,nacup_mark_planes,nacup_palette,16,16,1,4,0);sprite(&cup_sprite,nacup_cup_planes,nacup_palette,32,40,1,4,0);}
static void new_campaign(void){int i;for(i=0;i<4;i++)points[i]=0;race_no=wins=course_sel=0;money=70;hull=sails=crew=strategy=1;sponsor=0;last_prize=0;menu=0;screen=ST_TEAM;}
static void play_start_signal(int long_signal){prg32_audio_play_track((uint16_t)(long_signal?4:3));signal_sound_frames=long_signal?42:24;}
static void start_race(void){int i;wind_dir=(PREVAILING_SW_HEADING+31+(int)(rnd()%3))&31;wind_power=8+2*(int)(rnd()%5);race_clock=0;start_clock=START_COUNTDOWN_SECONDS;race_frames=0;start_line_active=1;top_view_mode=0;signal_sound_frames=0;for(i=0;i<4;i++){boats[i].team=(uint8_t)((team_sel+i)%4);boats[i].x=(boats[i].team&1)?238:82;boats[i].y=112+boats[i].team*4;boats[i].heading=16;boats[i].speed=0;boats[i].tack=1;boats[i].leg=boats[i].finished=boats[i].penalty=boats[i].spinnaker=boats[i].started=boats[i].entered_box=boats[i].tacking=boats[i].tack_timer=boats[i].penalty_turn=boats[i].rule=boats[i].mark_touch=0;boats[i].start_ready=0;boats[i].finish_time=0;}screen=ST_RACE;play_start_signal(0);}
static void score_race(void){int i,j;for(i=0;i<4;i++)result_order[i]=(uint8_t)i;for(i=0;i<4;i++)for(j=i+1;j<4;j++)if(boats[result_order[j]].finish_time<boats[result_order[i]].finish_time){uint8_t t=result_order[i];result_order[i]=result_order[j];result_order[j]=t;}for(i=0;i<4;i++){points[boats[result_order[i]].team]+=4-i;if(result_order[i]==0)player_rank=(uint8_t)(i+1);}last_prize=30-(player_rank-1)*7;if(player_rank==1){wins++;last_prize+=sponsors[sponsor].win_bonus;}money+=last_prize+sponsors[sponsor].fee;if(sponsor<3&&wins>=sponsors[sponsor+1].min_wins)sponsor++;}
static int upgrade_cost(int l){return 8+l*7;}static void update_manager(uint32_t p){int *v=0;if(p&PRG32_BTN_UP)menu--;if(p&PRG32_BTN_DOWN)menu++;menu=clamp(menu,0,5);if(menu==1)v=&hull;else if(menu==2)v=&sails;else if(menu==3)v=&crew;else if(menu==4)v=&strategy;if((p&PRG32_BTN_A)&&menu==0&&sponsor<3&&wins>=sponsors[sponsor+1].min_wins)sponsor++;else if((p&PRG32_BTN_A)&&v&&*v<8&&money>=upgrade_cost(*v)){money-=upgrade_cost(*v);(*v)++;}else if((p&PRG32_BTN_A)&&menu==5)screen=ST_BRIEF;if((p&PRG32_BTN_B)&&v&&*v>1){(*v)--;money+=upgrade_cost(*v)/2;}}
static int angle_diff(int a,int b){int d=(a-b)&31;if(d>16)d-=32;return d;}
static int heading_to(int dx,int dy){int ax=absi(dx),ay=absi(dy);if(ax*2<ay)return dy<0?0:16;if(ay*2<ax)return dx>0?8:24;if(dx>0)return dy<0?4:12;return dy<0?28:20;}
static const uint8_t polar_angle[11]={0,40,52,60,75,90,110,120,135,150,180};
static const uint8_t polar8[11]={0,63,71,74,76,76,76,74,68,57,50};
static const uint8_t polar12[11]={0,72,81,84,87,88,89,89,86,79,69};
static const uint8_t polar16[11]={0,75,84,88,91,93,94,96,94,91,82};
static int polar_at(const uint8_t *p,int twa){int i;for(i=1;i<11&&twa>polar_angle[i];i++){}if(i>=11)return p[10];return p[i-1]+(p[i]-p[i-1])*(twa-polar_angle[i-1])/(polar_angle[i]-polar_angle[i-1]);}
static int polar_speed10(int twa,int tws){int lo,hi;if(tws<=8)return polar_at(polar8,twa);if(tws>=16)return polar_at(polar16,twa);if(tws<=12){lo=polar_at(polar8,twa);hi=polar_at(polar12,twa);return lo+(hi-lo)*(tws-8)/4;}lo=polar_at(polar12,twa);hi=polar_at(polar16,twa);return lo+(hi-lo)*(tws-12)/4;}
static void award_penalty(boat_t *b,rule_t rule){if(!b->penalty){b->penalty=1;b->penalty_turn=0;b->rule=(uint8_t)rule;b->speed/=2;}}
static void physics(boat_t *b,int human,uint32_t in){int rel,twa,target,tb,course,new_tack,old_y=(int)b->y;if(b->finished)return;if(human){if(!(b->penalty&&(in&PRG32_BTN_B))){if(in&PRG32_BTN_LEFT)b->heading=(b->heading-1)&31;if(in&PRG32_BTN_RIGHT)b->heading=(b->heading+1)&31;}}else if(!b->penalty){if(!b->entered_box)course=16;else if(!b->started&&start_clock>0)course=b->y<START_LINE_Y+16?16:((b->team&1)?28:4);else if(!b->started&&!b->start_ready)course=16;else if(!b->started)course=b->x<START_LINE_LEFT+18?4:b->x>START_LINE_RIGHT-18?28:0;else if(b->leg<course_len[course_sel])course=heading_to(course_x[course_sel][b->leg]-(int)b->x,course_y[course_sel][b->leg]-(int)b->y);else course=heading_to(160-(int)b->x,FINISH_Y+8-(int)b->y);course+=(int)(rnd()%3)-1;if(angle_diff(course,b->heading)>0)b->heading=(b->heading+1)&31;else if(angle_diff(course,b->heading)<0)b->heading=(b->heading-1)&31;}rel=absi(angle_diff(b->heading,wind_dir));new_tack=angle_diff(b->heading,wind_dir)>=0?1:-1;if(new_tack!=b->tack&&rel<5){b->tacking=1;b->tack_timer=24;}b->tack=(int8_t)new_tack;if(b->tack_timer)b->tack_timer--;else b->tacking=0;twa=rel*180/16;if(!human)b->spinnaker=(uint8_t)(twa>=110);target=polar_speed10(twa,wind_power);if(twa>=100&&!b->spinnaker)target=target*72/100;if(twa<90&&b->spinnaker)target=target*55/100;if(start_clock>0)target=target*55/100;if(human)target=target*(94+hull*2+sails*2+strategy)/100;else target=target*(96+teams[b->team].speed)/100;tb=human?crew:teams[b->team].crew;if((frame%(11-tb/2))==0)b->speed+=(target-b->speed)/4;b->speed=clamp(b->speed,0,120);b->x+=(sin32[b->heading]*b->speed)/200;b->y-=(sin32[(b->heading+8)&31]*b->speed)/200;if(start_clock>120&&b->y>START_LINE_Y-7)b->y=START_LINE_Y-7;if(start_clock<=120&&!b->entered_box&&old_y<=START_LINE_Y&&b->y>START_LINE_Y&&((!(b->team&1)&&b->x>=START_BOX_LEFT&&b->x<160)||((b->team&1)&&b->x>160&&b->x<=START_BOX_RIGHT)))b->entered_box=1;if(start_clock>0)b->start_ready=(uint8_t)(b->entered_box&&b->y>START_LINE_Y);else if(!b->started){if(b->entered_box&&b->y>START_LINE_Y)b->start_ready=1;if(b->entered_box&&b->start_ready&&old_y>START_LINE_Y&&b->y<=START_LINE_Y&&b->x>=START_LINE_LEFT&&b->x<=START_LINE_RIGHT)b->started=1;}if(b->started&&b->leg<course_len[course_sel]&&absi((int)b->x-course_x[course_sel][b->leg])<18&&absi((int)b->y-course_y[course_sel][b->leg])<18){if(absi((int)b->x-course_x[course_sel][b->leg])<8&&absi((int)b->y-course_y[course_sel][b->leg])<8)b->mark_touch=1;b->leg++;}else if(b->started&&b->leg>=course_len[course_sel]&&old_y<FINISH_Y&&b->y>=FINISH_Y&&b->x>FINISH_BOAT_X+22&&b->x<FINISH_BUOY_X){b->finished=1;b->finish_time=(uint16_t)(race_clock+b->penalty*180);}b->x=clamp((int)b->x,-20,340);b->y=clamp((int)b->y,28,190);}
static void net_update(uint32_t in){int i;prg32_multiplayer_peer_t p;uint8_t flags=(uint8_t)((boats[0].leg&7)|((team_sel&3)<<3)|(boats[0].spinnaker?0x20:0)|(boats[0].started?0x40:0)|(boats[0].finished?0x80:0));nacup_net_publish((int)boats[0].x,(int)boats[0].y,boats[0].heading,in,flags);peer_count=(uint8_t)nacup_net_peer_count();for(i=0;i<peer_count;i++)if(nacup_net_peer(i,&p)){boat_t *b=&boats[i+1];uint8_t was_finished=b->finished;int8_t old_tack=b->tack;b->x=p.x;b->y=p.y;b->heading=(int16_t)(p.sprite&31);b->tack=(int8_t)(angle_diff(b->heading,wind_dir)>=0?1:-1);if(b->tack!=old_tack&&absi(angle_diff(b->heading,wind_dir))<5){b->tacking=1;b->tack_timer=24;}if(b->tack_timer)b->tack_timer--;else b->tacking=0;b->leg=p.flags&7;b->team=(p.flags>>3)&3;b->spinnaker=(p.flags&0x20)!=0;b->started=(p.flags&0x40)!=0;b->finished=(p.flags&0x80)!=0;if(!was_finished&&b->finished)b->finish_time=(uint16_t)race_clock;}}
static void update_lobby(uint32_t p){int i,all_ready;prg32_multiplayer_peer_t peer;if(p&PRG32_BTN_A)local_ready=1;if(p&PRG32_BTN_B){prg32_multiplayer_leave();multiplayer=0;peer_count=0;local_ready=0;start_race();return;}nacup_net_publish(0,0,team_sel,0,(uint8_t)(((team_sel&3)<<3)|(local_ready?0x40:0)));peer_count=(uint8_t)nacup_net_peer_count();all_ready=local_ready&&peer_count>0;for(i=0;i<peer_count;i++)if(!nacup_net_peer(i,&peer)||!(peer.flags&0x40))all_ready=0;if(all_ready)start_race();}
static int mark_dist2(const boat_t *b){int dx,dy;if(b->leg>=course_len[course_sel])return 99999;dx=(int)b->x-course_x[course_sel][b->leg];dy=(int)b->y-course_y[course_sel][b->leg];return dx*dx+dy*dy;}
static int windward_score(const boat_t *b){return (int)b->x*sin32[wind_dir]-(int)b->y*sin32[(wind_dir+8)&31];}
static void enforce_rules(void){int i,j;if(start_clock>240)return;for(i=0;i<4;i++)if(boats[i].mark_touch){award_penalty(&boats[i],RULE_MARK_TOUCH);boats[i].mark_touch=0;}for(i=0;i<4;i++)for(j=i+1;j<4;j++){boat_t *a=&boats[i],*b=&boats[j];int dx,dy,along,da,db,offender=-1;if(a->finished||b->finished)continue;dx=(int)b->x-(int)a->x;dy=(int)b->y-(int)a->y;if(dx*dx+dy*dy>=196)continue;a->speed/=2;b->speed/=2;if(dx>=0){a->x-=2;b->x+=2;}else{a->x+=2;b->x-=2;}if(dy>=0){a->y--;b->y++;}else{a->y++;b->y--;}if(a->penalty||b->penalty)continue;if(a->tacking!=b->tacking){offender=a->tacking?i:j;if(offender==i)award_penalty(a,RULE_TACKING);else award_penalty(b,RULE_TACKING);continue;}if(a->leg==b->leg&&a->leg<course_len[course_sel]){da=mark_dist2(a);db=mark_dist2(b);if(da<1600||db<1600){offender=da<=db?j:i;if(offender==i)award_penalty(a,RULE_MARK_ROOM);else award_penalty(b,RULE_MARK_ROOM);continue;}}if(a->tack!=b->tack){offender=a->tack<0?i:j;if(offender==i)award_penalty(a,RULE_PORT);else award_penalty(b,RULE_PORT);continue;}along=dx*sin32[a->heading]-dy*sin32[(a->heading+8)&31];if(absi(along)<300){int wa=windward_score(a),wb=windward_score(b);offender=wa>=wb?i:j;if(offender==i)award_penalty(a,RULE_WINDWARD);else award_penalty(b,RULE_WINDWARD);}else{offender=along>0?i:j;if(offender==i)award_penalty(a,RULE_ASTERN);else award_penalty(b,RULE_ASTERN);}if(offender<0){award_penalty(a,RULE_CONTACT);award_penalty(b,RULE_CONTACT);}}}
static void serve_penalty(boat_t *b,int active){if(!b->penalty||!active)return;b->speed=clamp(b->speed,0,18);b->heading=(b->heading+2)&31;b->penalty_turn=(uint8_t)(b->penalty_turn+2);if(b->penalty_turn>=32){b->penalty=0;b->penalty_turn=0;b->rule=RULE_NONE;}}
static void update_race(uint32_t in,uint32_t pressed){int i,first_ai=1,done=1,all_started=1,sim_pulse=0;if(signal_sound_frames>0&&--signal_sound_frames==0)prg32_audio_play_track(1);race_frames++;if(race_frames>=SIM_FRAMES_PER_SECOND){race_frames=0;sim_pulse=1;if(start_clock>0){start_clock--;if(start_clock==300||start_clock==240||start_clock==60)play_start_signal(0);else if(start_clock==0)play_start_signal(1);}else race_clock++;}if(pressed&PRG32_BTN_A)boats[0].spinnaker=!boats[0].spinnaker;if(sim_pulse&&start_clock==0&&race_clock&&race_clock%70==0)wind_dir=(PREVAILING_SW_HEADING+31+(int)(rnd()%3))&31;physics(&boats[0],1,in);if(multiplayer){net_update(in);first_ai=peer_count+1;}for(i=first_ai;i<4;i++)physics(&boats[i],0,0);enforce_rules();serve_penalty(&boats[0],(in&PRG32_BTN_B)!=0);for(i=first_ai;i<4;i++)serve_penalty(&boats[i],1);for(i=0;i<4;i++){if(!boats[i].started)all_started=0;if(!boats[i].finished)done=0;}if(all_started)start_line_active=0;if(race_clock>RACE_LIMIT_SECONDS)for(i=0;i<4;i++)if(!boats[i].finished){boats[i].finished=1;boats[i].finish_time=(uint16_t)(race_clock+600+i*30);}if((done&&start_clock==0)||race_clock>RACE_LIMIT_SECONDS){score_race();screen=ST_RESULT;menu=0;prg32_audio_play_track(2);}}
void nacup_init(void){setup_sprites();prg32_band_set_game_info("NaCup-napoli97 | portable 64 KiB | multiplayer");prg32_audio_play_track(0);screen=ST_TITLE;}
void nacup_update(void){uint32_t in=prg32_input_read(),p=in&~last_input;frame++;if(screen==ST_TITLE&&(p&PRG32_BTN_A))screen=ST_MODE;else if(screen==ST_MODE){if(p&(PRG32_BTN_UP|PRG32_BTN_DOWN))multiplayer=!multiplayer;if(p&PRG32_BTN_A)new_campaign();}else if(screen==ST_TEAM){if(p&PRG32_BTN_LEFT)team_sel=(team_sel+3)%4;if(p&PRG32_BTN_RIGHT)team_sel=(team_sel+1)%4;if(p&PRG32_BTN_A){menu=0;screen=ST_MANAGER;}}else if(screen==ST_MANAGER)update_manager(p);else if(screen==ST_BRIEF){if(p&(PRG32_BTN_LEFT|PRG32_BTN_UP))course_sel=(course_sel+COURSE_COUNT-1)%COURSE_COUNT;if(p&(PRG32_BTN_RIGHT|PRG32_BTN_DOWN))course_sel=(course_sel+1)%COURSE_COUNT;if(p&PRG32_BTN_A){if(multiplayer){peer_count=local_ready=0;if(nacup_net_join(course_sel))screen=ST_LOBBY;else multiplayer=0;}if(!multiplayer)start_race();}}else if(screen==ST_LOBBY)update_lobby(p);else if(screen==ST_RACE)update_race(in,p);else if(screen==ST_RESULT&&(p&PRG32_BTN_A)){if(multiplayer)prg32_multiplayer_leave();race_no++;if(race_no>=RACES)screen=ST_SEASON;else{menu=0;screen=ST_MANAGER;prg32_audio_play_track(0);}}else if(screen==ST_SEASON&&(p&PRG32_BTN_A)){screen=ST_TITLE;prg32_audio_play_track(0);}last_input=in;}
static void header(const char *t){prg32_gfx_rect(0,0,W,18,NAVY);prg32_gfx_text8(6,5,t,WHITE,NAVY);prg32_gfx_text8(238,5,"NAPOLI 1997",GOLD,NAVY);}
static void landscape(void){unsigned scene=(unsigned)(race_no%RACES),i=nacup_background_offsets[scene],end=nacup_background_offsets[scene+1];int x=0,y=27;prg32_gfx_rect(0,18,W,33,SKY);while(i<end){int count=nacup_background_rle8[i++];uint16_t color=nacup_background_palette[nacup_background_rle8[i++]];while(count){int width=count<320-x?count:320-x;prg32_gfx_rect(x,y,width,1,color);x+=width;count-=width;if(x==320){x=0;y++;}}}prg32_gfx_rect(0,51,W,15,SEA);}
static void draw_title(void){header("NaCup");landscape();nacup_draw_sprite(144,38,&cup_sprite,0);prg32_gfx_text8(49,91,"12-METRE AMERICA'S CUP",WHITE,SEA);prg32_gfx_text8(91,108,"NAPLES 1997",GOLD,SEA);prg32_gfx_text8(76,172,"PRESS A TO SET SAIL",WHITE,SEA);}
static void draw_mode(void){header("CHAMPIONSHIP MODE");box(48,48,224,78,GREY,NAVY);prg32_gfx_text8(77,67,"SINGLE PLAYER",!multiplayer?GOLD:WHITE,NAVY);prg32_gfx_text8(77,94,"NETWORK MULTIPLAYER",multiplayer?GOLD:WHITE,NAVY);prg32_gfx_text8(74,151,"UP/DOWN  A CONFIRM",WHITE,SEA);}
static void draw_team(void){int i;header("CHOOSE YOUR SYNDICATE");for(i=0;i<4;i++){int y=28+i*36;box(24,y,272,29,i==team_sel?GOLD:GREY,NAVY);prg32_gfx_rect(34,y+7,20,15,teams[i].color);prg32_gfx_text8(64,y+6,teams[i].name,WHITE,NAVY);prg32_gfx_text8(64,y+17,teams[i].code,GOLD,NAVY);}prg32_gfx_text8(55,178,"LEFT/RIGHT  A CONFIRM",WHITE,SEA);}
static void statrow(int y,const char *n,int v,int s){int i;prg32_gfx_text8(30,y,n,s?GOLD:WHITE,NAVY);for(i=0;i<8;i++)prg32_gfx_rect(132+i*13,y,10,7,i<v?CYAN:GREY);}
static void draw_manager(void){header("TEAM HQ");prg32_gfx_text8(12,24,teams[team_sel].name,GOLD,SEA);prg32_gfx_text8(164,24,"CASH K",WHITE,SEA);number(217,24,money,WHITE,SEA);box(16,38,288,133,GREY,NAVY);prg32_gfx_text8(30,49,sponsors[sponsor].name,menu==0?GOLD:WHITE,NAVY);number(222,49,sponsors[sponsor].fee,WHITE,NAVY);statrow(70,"HULL",hull,menu==1);statrow(88,"SAILS",sails,menu==2);statrow(106,"CREW",crew,menu==3);statrow(124,"STRATEGY",strategy,menu==4);prg32_gfx_text8(30,148,"RACE WEEKEND",menu==5?GOLD:WHITE,NAVY);prg32_gfx_text8(20,180,"A SIGN/INVEST/GO  B SELL",WHITE,SEA);}
static void draw_brief(void){header(race_names[race_no]);landscape();box(26,63,268,103,GREY,NAVY);prg32_gfx_text8(42,71,"SELECT RACE PATH",WHITE,NAVY);prg32_gfx_text8(42,85,course_names[course_sel],GOLD,NAVY);prg32_gfx_text8(42,102,"RRS 10-14, 18, 31 ACTIVE",WHITE,NAVY);prg32_gfx_text8(42,119,"SW BREEZE 8-16 KT / POLAR",WHITE,NAVY);prg32_gfx_text8(42,136,"A: SPIN  HOLD B: PEN TURN",CYAN,NAVY);prg32_gfx_text8(42,151,"LEFT/RIGHT CHOOSE  A GO",GOLD,NAVY);prg32_gfx_text8(83,177,"A - LEAVE DOCK",WHITE,SEA);}
static void draw_lobby(void){header("PRG32 MULTIPLAYER");box(45,38,230,108,GREY,NAVY);prg32_gfx_text8(72,49,"ROOM NACUP-NAPOLI97",GOLD,NAVY);prg32_gfx_text8(72,67,course_names[course_sel],CYAN,NAVY);prg32_gfx_text8(72,84,"PLAYERS",WHITE,NAVY);digit(133,84,peer_count+1,peer_count?GREEN:WHITE,NAVY);prg32_gfx_text8(145,84,"/ 4",WHITE,NAVY);prg32_gfx_text8(72,105,local_ready?"YOU ARE READY":"A - MARK READY",local_ready?GREEN:WHITE,NAVY);prg32_gfx_text8(72,126,peer_count?"WAITING FOR READY...":"WAITING FOR PEERS...",WHITE,NAVY);prg32_gfx_text8(69,157,"B - SOLO WITH AI",WHITE,SEA);}
static void draw_committee_boat(void){int mast_x=87;prg32_gfx_rect(74,148,27,4,WHITE);prg32_gfx_rect(78,152,19,3,NAVY);prg32_gfx_rect(mast_x,116,2,32,WHITE);prg32_gfx_rect(mast_x+2,118,10,7,0xfd20);if(start_clock>0){prg32_gfx_rect(mast_x+2,128,15,9,WHITE);prg32_gfx_text8(mast_x+5,129,"12",NAVY,WHITE);}if(start_clock<=240&&start_clock>60){prg32_gfx_rect(mast_x+2,139,15,9,NAVY);prg32_gfx_rect(mast_x+6,141,7,5,WHITE);}}
static void draw_start_signal(void){const char *msg;if(start_clock>300)msg="10 MIN - WARNING";else if(start_clock>240)msg="5 MIN - CLASS SIGNAL";else if(start_clock>120)msg="4 MIN - P FLAG UP";else if(start_clock>60)msg="2 MIN - ENTER THE BOX";else if(start_clock>0)msg="1 MIN - P FLAG DOWN";else msg="START - CLASS FLAG DOWN";prg32_gfx_rect(5,21,220,13,NAVY);prg32_gfx_text8(9,24,msg,start_clock?WHITE:GOLD,NAVY);}
static void draw_start_box(void){prg32_gfx_rect(START_BOX_LEFT,START_LINE_Y,1,START_BOX_BOTTOM-START_LINE_Y,GREY);prg32_gfx_rect(START_BOX_RIGHT,START_LINE_Y,1,START_BOX_BOTTOM-START_LINE_Y,GREY);prg32_gfx_rect(START_BOX_LEFT,START_BOX_BOTTOM,START_BOX_RIGHT-START_BOX_LEFT,1,GREY);prg32_gfx_rect(START_BOX_LEFT,START_LINE_Y-2,25,3,RED);prg32_gfx_rect(START_BOX_RIGHT-24,START_LINE_Y-2,25,3,GREEN);if(start_clock<=120&&start_clock>0){prg32_gfx_text8(31,158,"PORT",RED,SEA);prg32_gfx_text8(258,158,"STBD",GREEN,SEA);}}
static void target_box(int x,int y){uint16_t c=(frame&16)?GOLD:WHITE;prg32_gfx_rect(x-12,y-12,24,2,c);prg32_gfx_rect(x-12,y+10,24,2,c);prg32_gfx_rect(x-12,y-12,2,24,c);prg32_gfx_rect(x+10,y-12,2,24,c);prg32_gfx_text8(x-15,y-22,"NEXT",GOLD,SEA);}
static void draw_finish_boat(void){prg32_gfx_rect(FINISH_BOAT_X,FINISH_Y,27,4,WHITE);prg32_gfx_rect(FINISH_BOAT_X+4,FINISH_Y+4,19,3,NAVY);prg32_gfx_rect(FINISH_BOAT_X+13,FINISH_Y-25,2,25,WHITE);prg32_gfx_rect(FINISH_BOAT_X+15,FINISH_Y-23,11,8,0x001f);}
static void draw_course_marks(void){int i;for(i=0;i<course_len[course_sel];i++){int x=course_x[course_sel][i],y=course_y[course_sel][i];nacup_draw_sprite(x-8,y-8,&mark_sprite,0);if(boats[0].leg==i)target_box(x,y);}}
static void draw_finish_line(void){uint16_t c=boats[0].leg>=course_len[course_sel]?GOLD:WHITE;draw_finish_boat();prg32_gfx_rect(FINISH_BOAT_X+27,FINISH_Y,FINISH_BUOY_X-FINISH_BOAT_X-35,2,c);nacup_draw_sprite(FINISH_BUOY_X-8,FINISH_Y-8,&mark_sprite,0);if(boats[0].leg>=course_len[course_sel])target_box(FINISH_BUOY_X,FINISH_Y);}
static int close_to_rival_or_buoy(int limit){int i,dx,dy,l2=limit*limit;for(i=1;i<4;i++){dx=(int)boats[0].x-(int)boats[i].x;dy=(int)boats[0].y-(int)boats[i].y;if(dx*dx+dy*dy<=l2)return 1;}for(i=0;i<course_len[course_sel];i++){dx=(int)boats[0].x-course_x[course_sel][i];dy=(int)boats[0].y-course_y[course_sel][i];if(dx*dx+dy*dy<=l2)return 1;}dx=(int)boats[0].x-FINISH_BUOY_X;dy=(int)boats[0].y-FINISH_Y;return dx*dx+dy*dy<=l2;}
static void draw_top_view_grid(void){int x,y,px=(int)boats[0].x,py=(int)boats[0].y;for(x=0;x<W;x+=40)prg32_gfx_rect(x,18,1,163,0x1518);for(y=21;y<181;y+=32)prg32_gfx_rect(0,y,W,1,0x1518);prg32_gfx_text8(238,24,"TOP VIEW",GOLD,SEA);if(px>TOP_VIEW_ENTER)prg32_gfx_rect(px-TOP_VIEW_ENTER,py,8,1,CYAN);if(px<W-TOP_VIEW_ENTER)prg32_gfx_rect(px+TOP_VIEW_ENTER-7,py,8,1,CYAN);if(py>18+TOP_VIEW_ENTER)prg32_gfx_rect(px,py-TOP_VIEW_ENTER,1,8,CYAN);if(py<181-TOP_VIEW_ENTER)prg32_gfx_rect(px,py+TOP_VIEW_ENTER-7,1,8,CYAN);}
static void draw_course(void){int i,x,y;top_view_mode=(uint8_t)close_to_rival_or_buoy(TOP_VIEW_ENTER);prg32_gfx_clear(SEA);if(top_view_mode)draw_top_view_grid();else landscape();for(i=0;i<18;i++){x=(i*53+(int)(frame/3))%W;y=62+(i*37)%116;prg32_gfx_rect(x,y,10+(i&7),1,(i&1)?SKY:CYAN);}for(i=0;i<8;i++){x=(i*83-(int)(frame/5))%W;if(x<0)x+=W;y=76+(i*29)%98;prg32_gfx_rect(x,y,5+(i&3),1,WHITE);}draw_course_marks();if(start_line_active){draw_start_box();prg32_gfx_rect(START_LINE_LEFT,START_LINE_Y,START_LINE_RIGHT-START_LINE_LEFT,1,WHITE);draw_committee_boat();nacup_draw_sprite(START_LINE_RIGHT-8,START_LINE_Y-8,&mark_sprite,0);draw_start_signal();}else draw_finish_line();}
static const uint16_t *yacht_palette(uint8_t team){if((team&3)==0)return nacup_yacht_palette0;if((team&3)==1)return nacup_yacht_palette1;if((team&3)==2)return nacup_yacht_palette2;return nacup_yacht_palette3;}
static void draw_yacht(const boat_t *b){int x=(int)b->x-16,y=(int)b->y-16,sx,sy;unsigned heading=(unsigned)((b->heading>>1)&15);nacup_sprite_t *sprite=b->spinnaker?&spin_yacht_sprite:&jib_yacht_sprite;sprite->palette=yacht_palette(b->team);nacup_draw_sprite(x,y,sprite,heading);sx=x+15-sin32[b->heading]*11/31;sy=y+15+sin32[(b->heading+8)&31]*11/31;prg32_gfx_rect(sx,sy,3,3,teams[b->team].color);}
static void draw_race(void){int i;draw_course();for(i=3;i>=0;i--)draw_yacht(&boats[i]);header(race_names[race_no]);prg32_gfx_rect(0,181,W,19,NAVY);prg32_gfx_text8(5,187,start_clock?"T-":"R",start_clock?GOLD:WHITE,NAVY);clock_mmss(22,187,start_clock?start_clock:race_clock,start_clock?GOLD:WHITE,NAVY);prg32_gfx_text8(72,187,"KT",WHITE,NAVY);number(90,187,boats[0].speed/10,WHITE,NAVY);prg32_gfx_text8(108,187,"SW",CYAN,NAVY);prg32_gfx_text8(134,187,boats[0].spinnaker?"SPIN":"JIB",boats[0].spinnaker?GOLD:WHITE,NAVY);if(start_clock<=120&&!boats[0].entered_box)prg32_gfx_text8(177,187,(boats[0].team&1)?"ENTER STBD":"ENTER PORT",GOLD,NAVY);else if(!boats[0].started&&start_clock==0)prg32_gfx_text8(177,187,"CROSS LINE",GOLD,NAVY);else if(boats[0].penalty)prg32_gfx_text8(177,187,rule_names[boats[0].rule],RED,NAVY);else{prg32_gfx_text8(177,187,boats[0].leg<course_len[course_sel]?"NEXT":"FINISH",GOLD,NAVY);if(boats[0].leg<course_len[course_sel])digit(219,187,boats[0].leg+1,GOLD,NAVY);if(multiplayer){prg32_gfx_text8(244,187,"NET",GREEN,NAVY);digit(270,187,peer_count+1,GREEN,NAVY);prg32_gfx_text8(281,187,"/4",WHITE,NAVY);}}}
static void draw_result(void){int i;header("RACE RESULT");prg32_gfx_text8(20,28,"PLACE",WHITE,SEA);number(67,28,player_rank,GOLD,SEA);prg32_gfx_text8(126,28,"PRIZE K",WHITE,SEA);number(182,28,last_prize,GOLD,SEA);for(i=0;i<4;i++){const boat_t *b=&boats[result_order[i]];number(20,52+i*25,i+1,WHITE,SEA);prg32_gfx_text8(42,52+i*25,teams[b->team].name,b->team==team_sel?GOLD:WHITE,SEA);number(205,52+i*25,b->finish_time,WHITE,SEA);}prg32_gfx_text8(48,160,"SPONSOR PAYMENT RECEIVED",GREEN,SEA);prg32_gfx_text8(75,180,"A - NEXT RACE",WHITE,SEA);}
static void draw_season(void){int i,best=0;header("FINAL CLASSIFICATION");for(i=1;i<4;i++)if(points[i]>points[best])best=i;nacup_draw_sprite(144,27,&cup_sprite,0);prg32_gfx_text8(67,70,best==team_sel?"YOU WON THE AULD MUG":"THE CUP HAS A WINNER",GOLD,SEA);for(i=0;i<4;i++){prg32_gfx_text8(62,94+i*20,teams[i].name,WHITE,SEA);number(220,94+i*20,points[i],WHITE,SEA);}prg32_gfx_text8(63,180,"A - RETURN TO TITLE",WHITE,SEA);}
void nacup_draw(void){prg32_gfx_clear(SEA);if(screen==ST_TITLE)draw_title();else if(screen==ST_MODE)draw_mode();else if(screen==ST_TEAM)draw_team();else if(screen==ST_MANAGER)draw_manager();else if(screen==ST_BRIEF)draw_brief();else if(screen==ST_LOBBY)draw_lobby();else if(screen==ST_RACE)draw_race();else if(screen==ST_RESULT)draw_result();else draw_season();prg32_gfx_present();}
